pipeline:
    name: GitExp Example
    identifier: GitExp_Example
    projectIdentifier: GitExp_Doc_Example
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: example
              identifier: example
              description: ""
              type: CI
              spec:
                  cloneCodebase: false
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: example
                                identifier: example
                                spec:
                                    connectorRef: <+input>
                                    image: <+input>
                                    command: echo "hello world"
                                    privileged: false
                  serviceDependencies: []
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          namespace: <+input>
